language: java

jdk:
  - oraclejdk8


sudo: false

script: mvn clean verify

notifications:
  email:
    recipients:
      - fjunior.aragao@gmail.com
      - jose.rafael.feitosa@gmail.com
    on_success: always
